### ISSUE TITLE
Suggestions to get closer to JSON Schema and current OpenAPI variant

### ISSUE THREAD

**Issue by ucarion** [jddf/spec#2]
> This issue is copied from https://github.com/json-schema-language/spec/issues/11 which, for convenience to readers, I am copy-pasting here. Everything in this comment (including the title of this issue), aside from the current paragraph, is the words of @epoberezkin, not mine.

- elements. Why not “items"? Lots of people would feel more at home and it would simplify migration to JSL - more schemas would just work out of the box.
- no “nullable". It’s a very common use case that the value can be null. I would suggest adding to type form nullable: true
- tag. Why not “discriminator” for clarity of the form and consistency with OpenAPI?
- "strict instance semantics": suggest make it default and recommend that implementations support non-strict mode. What is the reason to create ambiguity here?
- "Implementations SHOULD support producing errors in this standard form." - suggest MUST
- "types": feels like there are too many, also "timestamp" as a type is very strange... I understand that the idea could be to match SQL or some language types, but depending on the language there may be other types... I would just follow JSON Schema: string, number, integer (or maybe "int" and "uint"), boolean. Also why would you not accept integer where float is expected (I mean what's the use case to require "float" at all)? Multiple types feel like some bad substitution for value ranges tbh that many people would miss... Also maybe we can have optional "size" in bytes for both strings and numbers, instead of multiple types?
- why no JSL for schema itself?
- how to link multiple files? or it's for implementations to decide?

The rest looks good.

Happy to make PRs for this items

---

also: require (allow?) type array/object (but must be compatible with the form). If you require, you would be able to define loose meta-schema for all forms.
For object, there is no reason not to consider discriminator and properties as one form allowing all three keywords, where in case of discriminator, properties and optionalProperties would define shared properties for all mappings - it would also allow to define the schema for tag e.g. string or number as you cannot imply it from the schema.

So in general, love the simplicity, but it violates "explicit better than implicit" idea and does not allow creating meta-schema. It would be very easy to rectify.

---

One more thing:

"values": I would allow schema for "keys", particularly if you support "size" in addition to "type". That would allow defining sparse arrays for example or limit the size of the dictionary keys.

**Comment by ucarion** [comment]
> elements. Why not “items"? Lots of people would feel more at home and it would simplify migration to JSL - more schemas would just work out of the box.

I'm sympathetic to the "feel more at home" argument. I chose `elements` because it seems a more precise word than `items`. From talking with folks, people unfamiliar with JSON Schema and JDDF seemed to usually guess that `items` would validate (key, value) pairs of an object, rather than the elements of an array. I don't think any word is going to be precise enough for people to guess its meaning without consulting docs.

I don't think I agree about "just work out of the box" -- in practice, I suspect very few schemas are going to be compatible with both JSON Schema and JDDF; in other words, I think that ship has sailed.

> no “nullable". It’s a very common use case that the value can be null. I would suggest adding to type form nullable: true

I'm open to this idea. As it's probably clear, in JDDF I've been trying to get away with as few features as possible. It was my suspicion that optional properties were good enough in many cases, and in other cases you can use an empty schema `{}`.

But perhaps I'm wrong, and nullable is not a feature we can live without. My concern is making sure that there is enough idiomatic support serializing/deserializing nullable JSON fields across mainstream languages.

> tag. Why not “discriminator” for clarity of the form and consistency with OpenAPI?

Are you suggesting that `tag` should be `propertyName` instead?

If so: because "tag" is the more precise, and widely used, term. For example, Wikipedia calls it a "tag" field in the introduction to: https://en.wikipedia.org/wiki/Tagged_union.

> "strict instance semantics": suggest make it default and recommend that implementations support non-strict mode. What is the reason to create ambiguity here?

If I understand what you're saying, I came to agree with you on this. Also, "strict" is not a very clear name, so I went with `additionalProperties: true/false` instead:

https://tools.ietf.org/html/draft-ucarion-jddf-05#section-3.1

> "Implementations SHOULD support producing errors in this standard form." - suggest MUST

Some implementations have good reason to not bother with standardized errors. For instance, if you're shoehorning JDDF into an interface where you can only return true/false, or if you're making an implementation meant to run on low-power devices where the extra error format is an unacceptable overhead.

If I said "MUST", then you're not implementing JDDF at all if you can't do the standard error messages. That seems too stringent.

All of the implementations in github.com/jddf support the standardized errors, as formalized in the test suite in this repo. Does that alleviate your concern?

> "types": feels like there are too many

I'm trying to have as few as I can get away with. I'm more than happy to scrutinize each of the things that exist.

> "timestamp" as a type is very strange... I understand that the idea could be to match SQL or some language types, but depending on the language there may be other types

It's pretty common in APIs, and is usually well-supported by the serialization/deserialization mechanisms of mainstream languages. It's not terribly hard to support, and users can stick with `string` if they want to use some other format for dates.

> I would just follow JSON Schema: string, number, integer (or maybe "int" and "uint"), boolean

The point of many of these extra types is code generation. That's why `float32` vs `float64` exists (because many, many languages distinguish the two), and open-ended `int` and `uint` types don't (instead, more specific `int8`, `int16`, `int32` exist).

> Also why would you not accept integer where float is expected

Can you clarify this question? I don't think I understand. Who is "you" in that sentence?

> Also why would you not accept integer where float is expected (I mean what's the use case to require "float" at all)?

`float32` vs `float64` exists because many languages distinguish the two, and that matters for code generation. Is that what you're asking about?

> Multiple types feel like some bad substitution for value ranges tbh that many people would miss

When you enter the world of value ranges, you're re-entering the rabbit-hole JSON Schema is stuck in, where basically you're writing a programming language in JSON. I'm limiting myself to features that correspond to the type systems of mainstream programming languages.

> Also maybe we can have optional "size" in bytes for both strings and numbers, instead of multiple types?

For strings, this seems like a bad idea. It requires assumptions around encoding of strings.

For numbers, this seems like a bad idea because it's already supported by the set of types already allowed. You can't reliably encode anything beyond `uint32` in JSON -- `int64`/`uint64` runs into the limitations of double-precision floating-point numbers.

> why no JSL for schema itself?

Are you asking why there's no "meta-schema"? Because it's not very necessary. For the purposes of writing a formal specification, CDDL is a much more powerful tool, and is already formalized as an RFC, unlike any other options.

> how to link multiple files? or it's for implementations to decide?

I've since removed the multi-file stuff in JDDF. Schemas are just one file. If you want to do "linking", you can write a linker / build your own linking stuff on top of JDDF.

> also: require (allow?) type array/object (but must be compatible with the form). If you require, you would be able to define loose meta-schema for all forms.

I don't understand this suggestion. Can you elaborate?

>  For object, there is no reason not to consider discriminator and properties as one form allowing all three keywords, where in case of discriminator, properties and optionalProperties would define shared properties for all mappings - it would also allow to define the schema for tag e.g. string or number as you cannot imply it from the schema.

Are you suggesting that this "schema":

```json
{
  "properties": { "a": { "type": "string" }},
  "optionalProperties": { "b": { "type": "string" }},
  "discriminator": {
    "tag": "foo",
    "mapping": {
      "v0": { "properties": { "x": { "type": "string" }}},
      "v1": { "properties": { "y": { "type": "string" }}}
    }
  }
}
```

Would be shorthand for:

```json
{
  "discriminator": {
    "tag": "foo",
    "mapping": {
      "v0": {
        "properties": {
          "a": { "type": "string" },
          "x": { "type": "string" }
        },
        "optionalProperties": {
          "b": { "type": "string" }
        }
      },
      "v1": {
        "properties": {
          "a": { "type": "string" },
          "x": { "type": "string" }
        },
        "optionalProperties": {
          "b": { "type": "string" }
        }
      },
    }
  }
}
```

?

> it would also allow to define the schema for tag e.g. string or number as you cannot imply it from the schema

I'm not sure I understand what you're saying here.

> "values": I would allow schema for "keys", particularly if you support "size" in addition to "type". That would allow defining sparse arrays for example or limit the size of the dictionary keys.

I think the discussion around "size" is relevant here again. It runs into problems of presuming stuff outside of JSON's purview, like how you encode strings. We don't need to solve every problem with JDDF, some things are better handled by other solutions.

**Comment by epoberezkin** [comment]
@ucarion I will split to several issues and link here

**Comment by epoberezkin** [comment]
- [x] items -> elements: #4
- [x] nullable -> #19
- [x] tag -> discriminator -> #20
- [x] strict instance semantics -> #21
- [x] errors in standard form - I agree with your arguments, resolved
- [x] number types #14
- [x] timestamp type #22
- [x] polymorphism and meta-schema #7
- [x] linking multiple files -> schema bundle #23
- [x] allow types array/object/struct/map: #5 
- [x] "keys" in addition to values: #24

**Comment by ucarion** [comment]
I take it we can close this issue once all relevant sub-issues are created?

**Comment by ucarion** [comment]
@epoberezkin Pinging on this issue -- can we create tickets and close this out?

**Comment by epoberezkin** [comment]
Ok to close (I can't as you created it)
